### ISSUE TITLE
Make `fv3fit` and `offline_ml_diags` compatible with 2D ML output variables

### ISSUE THREAD

**Issue by brianhenn** [VulcanClimateModeling/fv3net#1036]
Currently there are a bunch of (small) blockers which prevent:

- training a RF with only a 2D output variable(s) in `fv3fit`
- running `offline_ml_diags.compute_diags` with _any_ 2D output variables, plus additional blockers for computing diags with _only_ 2D output variables
- similar issues in `offline_ml_diags.create_report`

These can be resolved to allow 2D variables to be predicted, e.g. surface radiative flux biases

**Comment by AnnaKwa** [comment]
Resolved by https://github.com/VulcanClimateModeling/fv3net/pull/1127
