### ISSUE TITLE
nudge-to-fine workflow not updating SSTs

### ISSUE THREAD

**Issue by brianhenn** [VulcanClimateModeling/fv3net#1037]
The nudging runs are supposed to update coarse-model SSTs with the reference state but the N2F workflow in the sklearn_runfile is missing the actual state update call after it gets the reference SSTs:

https://github.com/VulcanClimateModeling/fv3net/blob/f646892b3c7fc752efadae9d70df94a45e512489/workflows/prognostic_c48_run/runtime/steppers/nudging.py#L89

**Comment by spencerkclark** [comment]
> The wrapper should override whatever the SST is set to in the fortran model; part of me wonders though whether we should verify this is still true since VulcanClimateModeling/fv3gfs-fortran#93 was merged.

My suspicion here was correct.  I have verified this with [a test in the Python wrapper](https://github.com/VulcanClimateModeling/fv3gfs-wrapper/pull/256).  Similar to the surface radiative fluxes, I think we will need to use a payload + namelist flag approach to setting this from Python.

**Comment by spencerkclark** [comment]
[This notebook](https://github.com/VulcanClimateModeling/explore/blob/master/spencerc/2021-03-23-test-sst-update/2021-03-23-verify-sst-setting.ipynb) illustrates that when completing a nudged run with the namelist flag added in VulcanClimateModeling/fv3gfs-fortran#173, that the SSTs are indeed modified when compared with a case without the namelist flag active.  No changes to fv3net beyond updating submodules will be needed.  Care will be needed to update configs for nudging runs, however; in those we should set the flag `gfs_physics_nml.override_sea_surface_temperature` to `.true.`.

**Comment by brianhenn** [comment]
So what were the differences in the notebook above from if they weren't from the nudging runs setting the SSTs?

**Comment by spencerkclark** [comment]
It's a little subtle.  If we do not set the SST via the wrapper, but use `Sfcprop%tsfco` as the sea surface temperature in the fortran, it stays set at its initial condition value.  In the default case, where we use `Sfcprop%tsfc` as the sea surface temperature in the fortran, it starts to follow the climatology.  So after two days, we can see a difference appearing.

**Comment by brianhenn** [comment]
Thanks that makes sense.

**Comment by spencerkclark** [comment]
#1101 adds the fix required to fv3net to take advantage of this.  Note per discussion with @mcgibbon I have modified the relevant namelist parameter in the fortran model.  It is now called `gfs_physics_nml.use_climatological_sst` and by default is set to `.true.`.  We must set it to `.false.` to enable overriding it in nudged runs.
