### ISSUE TITLE
Prognostic run: nudge to fine runs prone to I/O failures

### ISSUE THREAD

**Issue by brianhenn** [VulcanClimateModeling/fv3net#1136]
Nudge to fine runs depend on an `fs.get` call at each timestep to locally download the needed reference state data, which is proving to be unreliable: my recent experience is that 10-20% of 5-day runs fail with the below gcsfs error (not retried?) during the download. Outside of making gcsfs more reliable, immediate solutions might be to download all of the segment's reference states to disk at the run start (at least this would avoid getting 30 min into a segment and then failing), and adding retries around this download.

```
Traceback (most recent call last):
 File \"/tmp/tmp.IdNmPmtCHx/runfile.py\", line 50, in <module>
   for time, diagnostics in loop:
 File \"/fv3net/workflows/prognostic_c48_run/runtime/loop.py\", line 487, in __iter__
   diagnostics.update(substep())
 File \"/fv3net/workflows/prognostic_c48_run/runtime/loop.py\", line 420, in _compute_postphysics
   self._state.time, self._state
 File \"/fv3net/workflows/prognostic_c48_run/runtime/steppers/nudging.py\", line 42, in __call__
   reference = self._get_reference_state(time)
 File \"/fv3net/workflows/prognostic_c48_run/runtime/nudging.py\", line 120, in _get_reference_state
   fs.get(dirname, localdir, recursive=True)
 File \"/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py\", line 292, in get
   return sync(self.loop, self._get, rpaths, lpaths)
 File \"/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py\", line 71, in sync
   raise exc.with_traceback(tb)
 File \"/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py\", line 55, in f
   result[0] = await future
 File \"/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py\", line 280, in _get
   for lpath, rpath in zip(lpaths, rpaths)
 File \"/usr/local/lib/python3.6/dist-packages/gcsfs/core.py\", line 1116, in _get_file
   r.raise_for_status()
 File \"/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py\", line 1005, in raise_for_status
   headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://www.googleapis.com/download/storage/v1/b/vcm-ml-experiments/o/2020-06-02-fine-res%2Fcoarsen_restarts%2F20160908.214500%2F20160908.214500.fv_srf_wnd.res.tile6.nc?alt=media')
```

**Comment by oliverwm1** [comment]
> and adding retries around this download.

if you use gsutil for the download you can skip the retry logic. We use gsutil for uploading run output to GCS and it is rock solid and fast. Downside is the code might be a bit less clean.

**Comment by brianhenn** [comment]
Agreed that a gsutil solution might be the way to go.

**Comment by nbren12** [comment]
@martindurant Here are some good examples of reliability issues we've had in the past couple weeks with `gcsfs`. Happy to help here if you have any concrete suggestions.

@brianhenn I personally think we should try to stick with gcsfs. Using the `gsutil` command line from python makes the code much more complex.

My impression from my PR to gcsfs was that `fs.get/put` may hit more checksum/validation logic then `fs.cat`, but I'm not so sure now.

It looks like there are couple issues:
1. `.get` actually doesn't hit gcsfs's retry logic. The retry logic is in `fs._call` https://github.com/dask/gcsfs/blob/a63102e7f93959f4b1ec112f39e2933b923053aa/gcsfs/core.py#L515. But `_get_file` doesn't call ` _call` https://github.com/dask/gcsfs/blob/a63102e7f93959f4b1ec112f39e2933b923053aa/gcsfs/core.py#L1215. Perhaps we should contribute a fix to this upstream.
2. I'm not sure about the `.cat` error. How often does this happen?

**Comment by nbren12** [comment]
It would also be worth bumping to gcsfs 0.8.0, but I'm not sure that will solve these problems.

**Comment by martindurant** [comment]
Yes, please bump your version (and fsspec), since the event loop management should be more stable. I don't know if that has any effect for your situation, but it shouldn't hurt.

**Comment by martindurant** [comment]
> _get_file doesn't call _call

Agree that it ought, and it should not be hard to do.

**Comment by martindurant** [comment]
Does anyone on this thread have time to implement retries or routing through `_call`?

**Comment by nbren12** [comment]
Possibly. The retries seem easy, routing through call a little more involved. Is there good test coverage on `_get_file`? Last time I contributed the get/put tests were disabled.

**Comment by martindurant** [comment]
I think there might still be still a couple that run correctly against real GCS, but fail on VCR - so get xfail or skip in CI.

**Comment by nbren12** [comment]
Okay. I think the test coverage is pretty good when running locally. Looking at the code, routing through `_call` isn't possible w/o changing it. `_get_file` buffers it's read before dumping to disk, but `_call` reads it all in one go.

**Comment by martindurant** [comment]
ping me in the next couple of days and I can have a look. Having two places with retry would be OK, but one would be better!

**Comment by oliverwm1** [comment]
using the latest gcsfs, it sounds like @spencerkclark was able to do a long nudged run without any failures. Can we close this @brianhenn?
