### ISSUE TITLE
prognostic_run: sklearn runfile separation of concerns improvements

### ISSUE THREAD

**Issue by oliverwm1** [VulcanClimateModeling/fv3net#1164]
The logic of the prognostic run runfile is difficult to follow and extend. Here are a few particular issues with possible solutions. Taken from a slack thread with @nbren12.

1. ~remove the `tendency_variable` and `storage_variables` configurations and infer them from the diagnostics configs~
1. ~Rectify the weird coupling between `MonitoredPhysicsTimeLoop`, `monitor`, and `Loop` class. `monitor` is passed the entire time loop class which allows for weirdness.~
1. De-duplicate the copy/pasted code here: 
https://github.com/VulcanClimateModeling/fv3net/blob/149b545c5dd633cae746f938e84fb82906623bc0/workflows/prognostic_c48_run/runtime/diagnostics/machine_learning.py#L14-L17
1. ~refactor the specific humidity logging to the sklearn_runfile main. It is currently implemented here:~
https://github.com/VulcanClimateModeling/fv3net/blob/95a60a4fd7ac361ed57207a275a786050ea55f7f/workflows/prognostic_c48_run/runtime/loop.py#L413-L426
~but should be here:~
https://github.com/VulcanClimateModeling/fv3net/blob/74d9ba08e7496abcbb314b5d1258d7a700eb7c9e/workflows/prognostic_c48_run/sklearn_runfile.py#L55-L57
1. blow up the `get_diagnostics` and `get_momentum_diagnostics` methods of the Stepper classes
https://github.com/VulcanClimateModeling/fv3net/blob/149b545c5dd633cae746f938e84fb82906623bc0/workflows/prognostic_c48_run/runtime/steppers/machine_learning.py#L209-L214

Related: #1159, #896

**Comment by oliverwm1** [comment]
These points have all been resolved by above-referenced PRs.

**Comment by nbren12** [comment]
Thanks Oli! This was a great push to prep the prognostic run code for future development.
