### ISSUE TITLE
gcsfs: remove subtree once new release becomes available

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3net#1174]
dd610280df78e5d2b2351cb95dd0395963154541 adds gcsfs as a subtree to pull in some needed upstream bug fixes, and make them available for dataflow jobs.

This commit can be reverted once gcsfs v2021.04.1 is released, and the dataflow jobs updated to use this new release.

**Comment by oliverwm1** [comment]
Closed by #1258
