### ISSUE TITLE
Logging statements missing from prognostic run output

### ISSUE THREAD

**Issue by oliverwm1** [VulcanClimateModeling/fv3net#1350]
Various intended logging statements in the prognostic run do not appear in the output. I searched through a log file from a recent integration test run and found that the following are missing (this is an incomplete list):

https://github.com/VulcanClimateModeling/fv3net/blob/17b01e4fe52a01984b1978d961fd62e6f2411984/workflows/prognostic_c48_run/runtime/loop.py#L151

https://github.com/VulcanClimateModeling/fv3net/blob/17b01e4fe52a01984b1978d961fd62e6f2411984/workflows/prognostic_c48_run/runtime/loop.py#L171

https://github.com/VulcanClimateModeling/fv3net/blob/17b01e4fe52a01984b1978d961fd62e6f2411984/workflows/prognostic_c48_run/runtime/loop.py#L227

Some things that do appear in the logs:

https://github.com/VulcanClimateModeling/fv3net/blob/17b01e4fe52a01984b1978d961fd62e6f2411984/workflows/prognostic_c48_run/runtime/loop.py#L306-L309

https://github.com/VulcanClimateModeling/fv3net/blob/17b01e4fe52a01984b1978d961fd62e6f2411984/workflows/prognostic_c48_run/runtime/main.py#L59-L60

**Comment by nbren12** [comment]
This is probably caused by this line:
https://github.com/VulcanClimateModeling/fv3net/blob/17b01e4fe52a01984b1978d961fd62e6f2411984/workflows/prognostic_c48_run/runtime/segmented_run/run.py#L47

stdout is redirected to the logs file, but stderr is not.

**Comment by AnnaKwa** [comment]
According the StackOverflow posts I was referencing, that should combine `stderr` into the same stream as `stdout`: https://stackoverflow.com/a/7629651

I do have those python logging messages (minus the nudging, it was a baseline run) in some local prognostic runs that were run either off the commit that added the log streaming back or one very soon after it, so I think the cause might lie somewhere after that change.

**Comment by oliverwm1** [comment]
I verified that the python logging messages are all present in the logs output by the integration test on adf99fd264623fd9ce2689d6407ed6c14c4aa7bc so i can do a bisect since then.
